on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
      - name: Deploy RotaryAnalytics
        run: |
          ssh -i id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'bash -s' <<'ENDSSH'
            echo "Connected"
            cd /home/servicehost/go-rotaryanalytic 
            git stash
            git pull 
            cd /home/servicehost/go-rotaryanalytic/cmd
            # Temporarily fix the PATH to include typical directories where rm and sudo reside
            export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\$PATH
            go version
            rm -r rotaryAnalytics
            go build -o rotaryAnalytics
            sudo systemctl restart rotaryanalytic.service
            sudo systemctl status rotaryanalytic.service
          ENDSSH
